version: '3.8'

services:
  telegram-bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: telegram_ai_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_KEY=${API_KEY}
      - API_BASE_URL=${API_BASE_URL:-https://api.openai.com/v1}
      - MODEL=${MODEL:-gpt-4}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    depends_on:
      - redis
    networks:
      - bot-network
    labels:
      - "com.docker.compose.project=telegram-ai-bot"

  redis:
    image: redis:7-alpine
    container_name: telegram_bot_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 可选：监控服务
  monitoring:
    image: prom/prometheus:latest
    container_name: telegram_bot_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - bot-network
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  bot-network:
    driver: bridge
    name: telegram-ai-bot-network